### ISSUE TITLE
Doesn’t work with tonic 0.10.2

### ISSUE THREAD

**Issue by guaychou** [flemosr/envoy-types#2]
There is a lifetime issue when using 0.10.2 tonic. 

Please upgrade the deps of this crate.

I appreciate your work. You help to skip my tons of time to generate from protobuf

**Comment by flemosr** [comment]
@guaychou, thanks for the heads-up! We just merged a PR that should solve this, and I will be releasing a new version soon.

**Comment by flemosr** [comment]
@guaychou FYI, version 0.3.0 was released. Let me know if you are still facing issues!
